config/routes.rb
Rails.application.routes.draw do
  resources :shops
  root 'shops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_one_attached :image
  attribute :new_image

  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 100 }
  validates :opentime, length: { maximum: 20 }
  validates :closetime, length: { maximum: 20 }
  validates :holiday, length: { maximum: 30 }
  validates :hp, length: { maximum: 1000 }
  validates :tel, length: { maximum: 15 }
  validates :description, presence: true, length: { maximum: 1000 }
  
  before_save do
    self.image = new_image if new_image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to @shop, notice: "お店を登録しました。"
    else
      render :new
    end
  end

  def show
    @shop = Shop.find(params[:id])
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :description, :tel, :address, :hp, :opentime, :closetime, :holiday, :new_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ikenomy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Ikenomy", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Shop", new_shop_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shops/_form.html.erb
<%= form_with model: shop, local: true do |form| %>
  <%= render "shared/errors", obj: shop %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :new_image %>
    <%= form.file_field :new_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :tel %>
    <%= form.telephone_field :tel, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :hp %>
    <%= form.url_field :hp, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :opentime %>
    <%= form.time_field :opentime, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :closetime %>
    <%= form.time_field :closetime, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :holiday %>
    <%= form.text_field :holiday, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to '戻る', :back, class: "btn btn-secondary" %>
<% end %>

app/views/shops/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">お店登録</h2>
  <%= render 'form', shop: @shop %>
</div>

app/views/shops/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
      <% if @book.image.attached? %>
        <%= image_tag @shop.image.variant(resize: "300x300"), class: "img-thumbnail" %>
      <% else %>
        <%= image_tag "no_image.png", class: "img-thumbnail" %>
      <% end %>
    </div>

    <div class="col-md-8">
      <h2><%= @shop.name %></h2>
      <ul>
        <li><b>住所: </b><%= @shop.address %></li>
        <li><b>電話番号: </b><%= @shop.tel %></li>
        <li><b>開店時間: </b><%= @shop.opentime %></li>
        <li><b>閉店時間: </b><%= @shop.closetime %></li>
        <li><b>定休日: </b><%= @shop.holiday %></li>
        <li><b>HP: </b><%= @shop.hp %></li>
      </ul>
    </div>
  </div>
  <hr>
  <h4>お店の紹介</h4>
  <%= simple_format @shop.description %>
</div>